name: Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Jobs para build em desenvolvimento 
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    - name: Configura o JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Compila o projeto com Maven
      run: mvn -B compile --file pom.xml
  # Jobs para build em homologação
  build-hmg:
        runs-on: ubuntu-latest
        environment:
          name: hmg
        needs: build-dev
        steps:
        - name: Realiza o checkout do repositório
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Configura o JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
        - name: Testa o projeto com Maven
          env:
            DATABASE_URL: "jdbc:sqlite::memory:"
          run: mvn -B test --file pom.xml

      #Executaospassosda análisedo códigocom o sonarcube
        - name: Cache dos pacotesdo SonarCloud
          uses: actions/cache@v4
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os}}-sonar
            restore-keys: ${{ runner.os}}-sonar
        - name: Cache dos pacotesdo Maven
          uses: actions/cache@v4
          with:
            path: ~/.m2
            key: ${{ runner.os}}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os}}-m2
        - name: Verificao projetocom Maven e Jacoco
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}} 
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=B3ckeriz_A3- -Dsonar.organization=b3ckeriz -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        # Jobs para build em produção
  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-hmg
    steps:
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    - name: Configura o JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    # Executa o empacotamento do projeto com o Maven.
    # O parâmetro -DskipTests pula os testes pois já foram executados no ambiente anterior.
    - name: Empacota o projeto com Maven
      run: mvn -B package --file pom.xml -DskipTests
    # Cria o artefato de download
    - name: Crie uma pasta temporária de downloads de artefatos
      run: mkdir staging
    - name: Copia os artefatos a serem publicados na pasta temporária
      run: cp target/*jar-with-dependencies.jar staging
    - name: Usa Upload Artifact do GitHub Action
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
